### ISSUE TITLE
Why is an object passed by reference?

### ISSUE THREAD

**Issue by webarchitect609** [jimigrunge/invoke-private-methods#2]
The signature of `\Jimigrunge\InvokePrivateMethods\Traits\InvokePrivateMethodTrait::invokeMethod` method requires an object to be passed by reference. But in PHP all the objects are always passed by reference! Only variables can be passed by value or by reference. As a result the following code cannot be executed. And I believe that `&` can be safely removed. [Please, see my PR proving this](https://github.com/jimigrunge/invoke-private-methods/pull/1). I have also written all the needed Unit-tests and also appended 7.1, 7.2, 7.3 php versions to be tested against. 

```php
<?php

require __DIR__ . '/../vendor/autoload.php';

class Mothership
{
    /**
     * @var InnerComponent
     */
    protected $innerComponent;

    public function __construct()
    {
        $this->innerComponent = new InnerComponent();
    }

    /**
     * @return InnerComponent
     */
    private function getInnerComponent(): InnerComponent
    {
        return $this->innerComponent;
    }


}

class InnerComponent
{

}

$invokePrivateMethod = new \Jimigrunge\InvokePrivateMethods\InvokePrivateMethod();

$innerComponent = $invokePrivateMethod->invokeMethod(new Mothership(), 'getInnerComponent');
```

The error is `PHP Notice:  Only variables should be passed by reference in <filename> on line <linenumber>`. But I don't want to create any variable for the `Mothership`. I don't need it. I only want to get the `InnerComponent` and check if it is properly configured. 

P.S.: Thank you very much for such convinient tool! I wanted to write something like that, but careful research got me your package!!! Have no idea why such features are not included in PHPUnit from the box! :(

**Comment by jimigrunge** [comment]
@webarchitect609 Thank you for finding this. 

Constructing the class directly in the method call was not part of the initial requirements when this was created so was never considered. The reference itself is a throwback to older PHP5 practices that where being used in the project at the time. 

I will review your pull request.

**Comment by jimigrunge** [comment]
Pull request merged. Thank you @webarchitect609
